// Severity policy: a rule is at `error` or `off`, never `warn`. Every call site
// passes `--deny-warnings`. A rule the code will not follow is turned off here
// with a one-line reason, never disabled inline.
import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
  },

  plugins: ["typescript", "unicorn", "oxc", "import"],

  options: {
    typeAware: true,
  },

  // Vendored from github.com/dmmulroy/anti-slop, provenance in UPSTREAM.md.
  // The npm package `oxlint-plugin-anti-slop` is an unrelated name squat.
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],

  ignorePatterns: ["tools/oxlint/anti-slop/**"],

  rules: {
    "eslint/no-unused-vars": "error",
    "eslint/no-var": "error",
    "eslint/no-else-return": "error",
    "eslint/no-param-reassign": "error",
    // The write cycle is sequential by contract: backup, write, rename, read back.
    "eslint/no-await-in-loop": "off",
    "eslint/no-underscore-dangle": "error",
    "oxc/only-used-in-recursion": "error",
    "oxc/no-accumulating-spread": "error",
    "eslint/no-unmodified-loop-condition": "error",
    "eslint/no-unused-expressions": "error",
    "unicorn/error-message": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",

    "oxc/missing-throw": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/misrefactored-assign-op": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/uninvoked-array-callback": "error",
    "eslint/no-constant-binary-expression": "error",
    "eslint/no-template-curly-in-string": "error",
    "eslint/no-self-compare": "error",
    "eslint/no-loss-of-precision": "error",
    "eslint/no-promise-executor-return": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "eslint/no-new-wrappers": "error",
    "eslint/eqeqeq": "error",
    "eslint/array-callback-return": "error",
    "eslint/no-fallthrough": "error",
    "eslint/no-case-declarations": "error",
    "eslint/no-constructor-return": "error",
    "eslint/no-loop-func": "error",
    "eslint/no-unreachable": "error",
    "eslint/getter-return": "error",
    "eslint/no-redeclare": "error",
    "eslint/radix": "error",
    "eslint/no-object-constructor": "error",
    "eslint/no-prototype-builtins": "error",
    "eslint/no-throw-literal": "error",
    "unicorn/throw-new-error": "error",
    "unicorn/catch-error-name": "error",
    "eslint/no-empty": "error",
    "eslint/no-useless-return": "error",
    "eslint/require-await": "error",

    "import/no-default-export": "error",
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/consistent-type-specifier-style": "error",
    "import/no-mutable-exports": "error",
    "import/extensions": "error",
    "import/no-commonjs": "error",
    "import/no-dynamic-require": "error",
    "import/no-cycle": "error",
    "import/no-webpack-loader-syntax": "error",
    "import/no-unassigned-import": "error",

    "typescript/no-non-null-assertion": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/return-await": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/consistent-type-exports": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/only-throw-error": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-deprecated": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/strict-boolean-expressions": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/dot-notation": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/prefer-ts-expect-error": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-var-requires": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/array-type": "error",
    "typescript/prefer-function-type": "error",

    "unicorn/no-array-for-each": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/no-useless-undefined": ["error", { checkArguments: false }],
    "unicorn/no-useless-switch-case": "error",
    "unicorn/no-instanceof-array": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-global-this": "error",
    "unicorn/escape-case": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-useless-collection-argument": "error",
    "typescript/consistent-return": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/unified-signatures": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-includes": "error",
    "eslint/default-param-last": "error",
    "eslint/prefer-const": "error",
    "eslint/prefer-object-has-own": "error",
    "eslint/prefer-object-spread": "error",
    "eslint/prefer-template": "error",
    "eslint/default-case-last": "error",
    "eslint/no-lonely-if": "error",
    "eslint/curly": "error",

    // The quality gate of docs/rules: file 150, function 30, complexity 10, params 4, depth 3.
    "eslint/max-lines-per-function": [
      "error",
      { max: 30, skipBlankLines: true, skipComments: true, IIFEs: true },
    ],
    "eslint/complexity": ["error", { max: 10 }],
    "eslint/max-depth": ["error", { max: 3 }],
    "eslint/max-params": ["error", { max: 4 }],
    "eslint/max-lines": [
      "error",
      { max: 150, skipBlankLines: true, skipComments: true },
    ],

    "anti-slop/no-array-filter-map": "error",
    "anti-slop/no-reduce-accumulator-copy": "error",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    // The JSON decoders in src/json.ts are type guards: the only place typeof runs.
    "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-readable-spacing": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },

  overrides: [
    {
      files: ["**/*.test.ts"],
      rules: {
        // Under noUncheckedIndexedAccess a test reads a known fixture entry
        // with `!`; a failed read fails the test anyway.
        "typescript/no-non-null-assertion": "off",
        // A test builds stand-ins by asserting a partial object; the
        // production side needs the full type.
        "typescript/no-unsafe-type-assertion": "off",
        // bun:test types expect.any() and the asymmetric matchers as any.
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-argument": "off",
        // A describe callback is one function; the test body is capped by
        // max-statements instead, which also caps the tests per describe.
        "eslint/max-lines-per-function": "off",
        "eslint/max-statements": ["error", { max: 10 }],
      },
    },
    {
      // The QML engine (Qt 6.11) imports these modules as they are: it rejects object
      // spread and has no at(), toSorted(), toReversed(), flat(), flatMap(), replaceAll().
      files: ["gui/**/*.mjs"],
      rules: {
        "eslint/prefer-object-spread": "off",
        "unicorn/prefer-at": "off",
        "unicorn/no-array-sort": "off",
        "unicorn/no-array-reverse": "off",
        "unicorn/prefer-array-flat": "off",
        "unicorn/prefer-array-flat-map": "off",
        "unicorn/prefer-string-replace-all": "off",
      },
    },
    {
      // Tool contract: oxlint and oxfmt load their config as the default export;
      // the rule table is a list, not code.
      files: ["*.config.ts"],
      rules: { "import/no-default-export": "off", "eslint/max-lines": "off" },
    },
  ],
});
